// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCasZ02hdVZ9xkThX-ZtyPlFA5WyB7QoeM',
    appId: '1:1087359245232:web:527504bb41e88f340fd475',
    messagingSenderId: '1087359245232',
    projectId: 'urun-takip-fd8b8',
    authDomain: 'urun-takip-fd8b8.firebaseapp.com',
    storageBucket: 'urun-takip-fd8b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnNxtAr63Ir3Hyf7P_9e31qzzrd4OrCXg',
    appId: '1:1087359245232:android:d3ea9e47510c26390fd475',
    messagingSenderId: '1087359245232',
    projectId: 'urun-takip-fd8b8',
    storageBucket: 'urun-takip-fd8b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_1qMe5biPG908YZPc5xh_QIj49Q1LXCE',
    appId: '1:1087359245232:ios:d38c8093b3e7fd350fd475',
    messagingSenderId: '1087359245232',
    projectId: 'urun-takip-fd8b8',
    storageBucket: 'urun-takip-fd8b8.appspot.com',
    iosClientId: '1087359245232-pnhsqiq1inqd1j3dmafa6uassh8i0ql9.apps.googleusercontent.com',
    iosBundleId: 'com.example.urunTakipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_1qMe5biPG908YZPc5xh_QIj49Q1LXCE',
    appId: '1:1087359245232:ios:d38c8093b3e7fd350fd475',
    messagingSenderId: '1087359245232',
    projectId: 'urun-takip-fd8b8',
    storageBucket: 'urun-takip-fd8b8.appspot.com',
    iosClientId: '1087359245232-pnhsqiq1inqd1j3dmafa6uassh8i0ql9.apps.googleusercontent.com',
    iosBundleId: 'com.example.urunTakipApp',
  );
}
